---
title: "Code_pmids"
author: "Dorothy Bishop"
date: "2025-08-09"
output: html_document
---

Reads the list of PMIDs so that can see when a specific reviewer is a coauthor and include this in heatmap

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(here)
require(TSDT) #for unfactor function ?may not be used

require(stringr)
require(ggpubr) #organise plots - not currently used
library(reshape) #for melt function for geom
library("xlsx") #read and write xlsx files

```

NB can get authors for each PMID by search in PubMed, it accepts a list of PMIDS separated by OR and you can then export as csv.

Specify a string without odd characters in it to match to names in PMID list

```{r pmidread}
reviewers<-c("Etrusco","Giannini","Lagan","Signore","Sorrentino","Bogani","Cuccu","D'Oria","Ganduscio","D'Aug","Donato")
revfull<-c("Andrea Etrusco" ,"Andrea Giannini","Antonio Simone Laganà","Fabrizio Signore","Felice Sorrentino","Giorgio Bogani","Ilaria Cuccu","Ottavia D'Oria","Silvia Ganduscio","Tullio Golia D'Augè","Violante Di Donato")

#we'll just keep those who did at least 2 revs
revselect<- c(1,2,3,6,7,8,10,11)
reviewers<-reviewers [revselect]
revfull <- revfull[revselect]
nrev<-length(reviewers)

pmids <- read.csv('PMIDS_with_aus.csv')
pmids<-pmids[,c(1,3)] #only need PMID and Authors
#pmids$PMID <-str_trim(pmids$PMID)

temp<-data.frame(matrix(0,nrow=nrow(pmids),ncol=nrev))
names(temp)<-revfull
pmids<-cbind(pmids,temp)
for(i in 1:nrow(pmids)){
  for(r in 1:nrev){
    pmids[i,(r+3)]<-0
   g <- grep(reviewers[r],pmids$Authors[i])
   if(length(g)>0) {pmids[i,(r+2)]<-1}
   
  }
}
write.xlsx(pmids,"PMIDS_refs.xlsx")

# pmidlist<-pmids$PMID
# w<-which(pmidlist=='') #kludge - can't get rid of last blank one in original file!
# if(length(w)>0){pmidlist<-pmidlist[-w]}
# w<-which(pmidlist=='without PMID') #kludge - can't get rid of last blank one in original file!
# if(length(w)>0){pmidlist<-pmidlist[-w]}
```

```{r readmaindf}

df <- read.xlsx('Data set 30 Aug.xlsx',sheetIndex=1)
saveRDS(df, file = "dfimported30Aug.rds")
#we'll cut out unwanted columns
wantcols <- c('REVIEWER','REVIEWED.ARTICLE.PUBLISHER','REVIEWED.ARTICLE.DOI',
              'Stock.phrases.included','PMIDs.mentioned','PMID.in.final.version.refs')
df<-df[,wantcols]
names(df)<-c('Reviewer','Publisher','DOI','Boilerplate','PMID','cited')

#only retain those that match names

#df<-df[nchar(df$Boilerplate)>0,]

```

```{r pmidtable}
allrevs<-unique(df$Reviewer)[1:11] #original list of named ones
allrevs<-allrevs[order(allrevs)] #alphabetic
allrevs<-allrevs[revselect]
mytab<-data.frame(matrix(0,nrow=nrow(pmids),ncol=(1+length(allrevs))))
names(mytab)<-c('PMID',allrevs)
mytab$PMID<-pmids$PMID
pmidlist<-pmids$PMID


 for (i in 1:length(pmidlist)){
  for (a in 1:length(allrevs)){
  myset <- df$PMID[df$Reviewer==allrevs[a]]
    for (s in 1:length(myset)){
    g <- grep(pmidlist[i],myset[s])
    if(length(g)>0)
      {mytab[i,(a+1)]<-mytab[i,(a+1)]+1}
    }
  }
 }


```

```{r trygeomtile}

thistab<-mytab #for PMIDS
#add the N times PMID was cited in brackets after PMID
thistab$citecount<-0
thistab$trycoerce<-0
for (i in 1:nrow(df)){
  for(j in 1:length(pmidlist)){
      g <- grep(pmidlist[j],df$cited[i])
        if(length(g)>0)  {thistab$citecount[j]<-thistab$citecount[j]+1}   
      h <- grep(pmidlist[j],df$PMID[i])
      if(length(h)>0)  {thistab$trycoerce[j]<-thistab$trycoerce[j]+1}
  }
}
thistab$PMID<-paste0(thistab$PMID," (",thistab$citecount,")") #incorporate cite count in PMID

plot(jitter(thistab$trycoerce),jitter(thistab$citecount))

# nc<-ncol(thistab) #then delete citecount column
# thistab<-thistab[,-nc]
nrevs<-length(allrevs)
mytab2<-as.matrix(thistab[,2:(nrevs+1)])


revcount<-as.vector(table(df$Reviewer[df$Reviewer %in% revfull]))#N reviews by each reviewer
revlabels<-paste0(allrevs," \n(",revcount," reviews)")


# Transform the matrix in long format
dfm<- melt(mytab2)
dfm$X1<-thistab[,1] #copies labels into 1st col


colnames(dfm) <- c("x", "Reviewer","value")
dfm$isauthor<-0
#we'll now add a column that indicates if Reviewer was an author on that PMID
for (i in 1:nrow(dfm)){
  thisrev<-dfm$Reviewer[i]
  thisp <- dfm$x[i]
  plen<-length(thisp)
  s<-unlist(str_split_1(thisp," "))[[1]]
  w<-which(pmidlist == s)
  ww<-which(allrevs==thisrev)
  dfm$isauthor[i]<-pmids[w,(ww+2)]

}
  #change isauthor to a colour
dfm$marker<-''
dfm$marker[dfm$isauthor==1]<-'*'

dfm$valuex<-paste0(dfm$value,dfm$marker)

```

```{r makemap}


# Plot heatmap with values
g <- ggplot(dfm, aes(x = Reviewer, y = x, fill = value, label = valuex,color=color)) +
  geom_tile(color = "white") + # Create heatmap
  geom_text(color = "black", size = 1)+ # Add text labels
  scale_fill_gradient(low = "white", high = "cornflowerblue") + # Set color gradient
  theme_minimal() + # Set theme
  labs(x = "", y = "") + 
 scale_x_discrete(labels=revlabels)+ # Labels
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1,size=6))+
  theme(axis.text.y = element_text(size=6))

```
